### ISSUE TITLE
Error: Unknown dialect mysql

### ISSUE THREAD

**Issue by imvcsticorp** [usil/fields-multiverse#6]
Se hizo lo especificado en el acápite de Developer Mode, del archivo README.md, de la app Fields Multiverse 

## Developer mode

- Configure the [Requirements](#requirements)
- Create a database inside mysql instance with name "fields_multiverse_db"
- create .env file and copy content of https://github.com/usil/fields-multiverse/wiki/Env-variables-Generic customizing with your own values

- Excute this for Linux, mac, and windows git bash:

```sh
export $(cat .env | xargs)
npm install
npm run develop

## Current Behavior
Se muestra el error: Error: Unknown dialect mysql, en el GIT BASH, al ejecutar los comandos indicados.

## Possible Solution


## Steps to Reproduce
Adjunto los pantallazos de MySQL 8.1 Command Line Client y el GIT BASH, donde se ejecutaron los comandos indicados y el resultado de estos:

![MicrosoftTeams-image (12)](https://github.com/usil/fields-multiverse/assets/140431121/326aa768-e7d9-4f44-9a6c-3cfb84eea8eb)
![MicrosoftTeams-image (11)](https://github.com/usil/fields-multiverse/assets/140431121/b7e7c872-7ef5-4437-af0e-3e04f8291df5)
![MicrosoftTeams-image (10)](https://github.com/usil/fields-multiverse/assets/140431121/d877a1ac-3bc3-4a22-9a63-77373abd92a3)


## Context (Environment)
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

<!--- Provide a general summary of the issue in the Title above -->

## Detailed Description
<!--- Provide a detailed description of the change or addition you are proposing -->

## Possible Implementation
<!--- Not obligatory, but suggest an idea for implementing addition or change -->

**Comment by imvcsticorp** [comment]
![MicrosoftTeams-image (12)](https://github.com/usil/fields-multiverse/assets/140431121/92af2840-04d6-4d6a-9e9d-bae7077c5c68)
![MicrosoftTeams-image (11)](https://github.com/usil/fields-multiverse/assets/140431121/d9a0c45c-1310-4693-b93b-7ddb2acb004d)
![MicrosoftTeams-image (10)](https://github.com/usil/fields-multiverse/assets/140431121/9620eadd-d606-4eef-8502-4adee40081ec)

**Comment by jrichardsz** [comment]
No estas exportando las variables de entorno

https://stackoverflow.com/questions/70404776/error-unknown-dialect-undefined-when-deploying-strapi-4-0-app-to-heroku

- En linux se levanta en 2 minutos.
- En windows se ha probado 2 veces y se levanta en 10 minutos

Investigar que es variable de entorno y configurar su ambiente de desarrollo
